### ISSUE TITLE
mysql - docker compose 세팅

### ISSUE THREAD

**Issue by gdtknight** [FastCampus-Mini5/backend_server#3]
- `compose.yml` (추가 예정)
```yml
version: '3'

services:
  mysql:
    container_name: mini_mysql
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: ${MINI_USER}
      MYSQL_PASSWORD: ${MINI_PASSWORD}
      MYSQL_DATABASE: ${MINI_DATABASE}
    ports:
      - ${MINI_PORT_MAPPING}
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
```

- 해당 컨테이너 세팅에 필요한 환경변수 내용들은 `.env` 파일에 작성해서 슬랙 DM으로 공유할 예정.
- 추후 `CI/CD` 는 일단은 배제하고 `AWS EC2` 에 직접 프로젝트 업로드하고, 프로젝트 루트 디렉토리에 `.env` 파일 수동으로 생성해서 실행하는 것으로 예상 중

- 테스트는 어차피 h2 로 진행할 예정 (인 것으로 알고 있음) -> 개발 과정에서는 중요도 ↓ (낮음)
- 최종 빌드 완료된 jar 파일 포함하는 docker image 새로 생성해도 좋을 것으로 예상 ~(But, 잘 몰라요)~
